spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

clients:
  users-api-host: https://cgjresszgg.execute-api.eu-west-1.amazonaws.com/users
  teams-api-host: https://cgjresszgg.execute-api.eu-west-1.amazonaws.com/teams
