spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://mysql:3306/test?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

clients:
  users-api-host: https://cgjresszgg.execute-api.eu-west-1.amazonaws.com/users
  teams-api-host: https://cgjresszgg.execute-api.eu-west-1.amazonaws.com/teams
